In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import helper as hlp

# Loading data
data = np.load('data2D.npy')
#data = np.load('data100D.npy')
[num_pts, dim] = np.shape(data)

# For Validation set
valid_batch = int(num_pts / 3.0)
np.random.seed(45689)
rnd_idx = np.arange(num_pts)
np.random.shuffle(rnd_idx)
val_data = data[rnd_idx[:valid_batch]]
data = data[rnd_idx[valid_batch:]]

print (num_pts, dim)

10000 2


In [5]:
print ("valid_batch")
print (valid_batch)
print ("rnd_idx")
print (rnd_idx)
print ("val_data")
print (val_data)
print ("data")
print (data)

valid_batch
3333
rnd_idx
[2651 6985 1054 ... 2427 4269 2275]
val_data
[[ 1.25852288  0.06022857]
 [ 0.92050755 -1.35582494]
 [ 1.68880499  0.19383041]
 ...
 [-0.39069652 -0.73439272]
 [-1.06336658 -3.17085342]
 [ 1.48777099  0.05273467]]
data
[[-1.29816288 -3.26433091]
 [-1.14550332 -3.23405831]
 [-0.58079709 -3.71435242]
 ...
 [ 1.89505235 -1.11184279]
 [ 1.55736498  0.01002898]
 [ 0.62464409 -1.02498467]]


In [ ]:
# Distance function for K-means
def distanceFunc(X, MU):
    # Inputs
    # X: is an NxD matrix (N observations and D dimensions)
    # MU: is an KxD matrix (K means and D dimensions)
    # Outputs
    # pair_dist: is the pairwise distance matrix (NxK)
    # TODO
    tf.reduce_sum(tf.square(tf.sub(X,MU)),2)

In [2]:
def k_means():
    assignments = tf.argmin(distances,0)

SyntaxError: unexpected EOF while parsing (<ipython-input-2-3fcec64cee8d>, line 1)